// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2AGFbwEqrQhgbbZs8lUUEC_6v28EBQWU',
    appId: '1:700227288696:web:b0badc7f7310304254f78d',
    messagingSenderId: '700227288696',
    projectId: 'e-commerce-sh-76fe6',
    authDomain: 'e-commerce-sh-76fe6.firebaseapp.com',
    storageBucket: 'e-commerce-sh-76fe6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCk7BlcEQjXWHjU3vzxvvpova1JbrtsUs',
    appId: '1:700227288696:android:752d19ea33f8539354f78d',
    messagingSenderId: '700227288696',
    projectId: 'e-commerce-sh-76fe6',
    storageBucket: 'e-commerce-sh-76fe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6z6qSu3VIQX3PFvplETZ7vq_1dBcqA_k',
    appId: '1:700227288696:ios:b1bd6da73e01242054f78d',
    messagingSenderId: '700227288696',
    projectId: 'e-commerce-sh-76fe6',
    storageBucket: 'e-commerce-sh-76fe6.appspot.com',
    androidClientId: '700227288696-gao2re9spk39bdbrpm4rbru0co8u3eo9.apps.googleusercontent.com',
    iosClientId: '700227288696-q8iesvl4j5oau73jmaituq08l9vbp8kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

}